export const defaultConfig = {
  general: {
    "open-control-at-launch": true,
    "open-display-at-launch": true,
    language: "en",
  },
  display: {
    "display-mode": "displayFullScreen",
    "pixel-ratio": "retina",
    "show-fps": false,
    antialias: true,
    "click-through": "all",
    "keep-display-at-top": true,
    "show-in-all-workspaces": true,
    background: "#000000",
    "2d-initial-width-range": [75, 100],
    "2d-initial-height-range": [20, 100],
    "2d-draggable": true,
    "3d-outline-effect": true,
    // "model-mouse-track": true,
    // "3d-physics-simulation": true,
    // "3d-camera-type": "perspective",
    // "dynamic-params-sync": true,
    // "params-sync-frequency": "system",
  },
};
