export const defaultConfig = {
  general: {
    "open-control-at-launch": true,
    "open-display-at-launch": true,
    language: "en",
  },
  display: {
    "display-mode": "displayFullScreen",
    "pixel-ratio": "retina",
    "show-fps": true,
    antialias: true,
    "click-through": "all",
    "display-range": "singleDesktop",
    "keep-display-at-top": true,
    background: "#000000",
    "live2d-initial-width-range": [65, 100],
    "live2d-initial-height-range": [20, 100],
    "live2d-draggable": true,
    "spine-initial-width-range": [75, 100],
    "spine-initial-height-range": [75, 100],
    "spine-draggable": true,
    "spine-premultiply-alpha": false,
    "mmd-outline-effect": true,
    "mmd-orbit-controls": true,
    "vroid-outline-effect": false,
    "vroid-orbit-controls": true,
    // "model-mouse-track": true,
    // "3d-physics-simulation": true,
    // "3d-camera-type": "perspective",
    // "dynamic-params-sync": true,
    // "params-sync-frequency": "system",
  },
};
